export const productsDummy = [
  {
    category_id: 1,
    category_name_en: null,
    category_name_ar: "Shoes",
    details_en: null,
    details_ar: "المنتجات الملموسه والقابله للشحن",
    created_at: "2024-12-12T14:52:26.346",
    updated_at: "2025-01-16T05:43:55.1400574",
    brandsDto: [
      {
        brand_id: 1,
        brand_name: "shoes",
        details: "عامه",
        add_to_main_brand: true,
        created_at: null,
        updated_at: null,
        productDto: [
          {
            product_id: 1,
            product_name_en: null,
            product_name_ar: "shoes01",
            price: 150,
            photoes: [
              "linda-xu-fUEP0djb1hA-unsplash.jpg",
              "malvestida-DMl5gG0yWWY-unsplash.jpg",
            ],
            description_en: null,
            description_ar: "string",
            created_at: "2025-01-16T05:48:32.320989",
            updated_at: "2025-01-16T05:48:32.3210306",
            rating_number: 0,
            productDetailDto: [
              {
                product_details_id: 1,
                cost_price: 0.0,
                price: 0.0,
                price_after_discount: 0.0,
                end_discount_date: "string",
                store_code: "string",
                gtin: "string",
                mpn: "string",
                trade_mark: 1,
                second_address: "string",
                ads_address: "string",
                discount: 0,
                percent: 0,
                amount_options: "string",
                product_view_channels: "string",
                file_attach: true,
                write_note: true,
                under_taxes: true,
                details_en: null,
                details_ar: "string",
                weight: 0,
                tags: "string",
                is_featured: true,
                rate: 0,
                rate_details: "string",
                created_at: null,
                updated_at: null,
              },
            ],
            alertsDto: [
              {
                alert_id: 1,
                amount: 0,
                amount_of_clients: 0,
                percentt: 0,
                created_at: null,
                updated_at: null,
              },
            ],
            product_colors: [
              {
                product_colors_id: 1,
                color_name: "red",
                price: 0.0,
                hex_code: "red",
                created_at: "2025-01-16T05:48:32.6768713",
                updated_at: "2025-01-16T05:48:32.6772815",
                photoes: [
                  "linda-xu-fUEP0djb1hA-unsplash.jpg",
                  "malvestida-DMl5gG0yWWY-unsplash.jpg",
                ],
                size: ["41", "42", "43", "44", "45"],
                size_price: ["50", "60", "70", "80", "90"],
                cost: ["120", "130", "140", "150", "160"],
                quantity: ["5", "6", "7", "8", "9"],
              },
            ],
            attached_filesDto: [
              {
                attached_files_id: 1,
                attached_file_name: "string",
                attached_file_details: "string",
                created_at: null,
                updated_at: null,
              },
            ],
            seo_detailsDto: [
              {
                seo_details_id: 1,
                page_title: "string",
                seo_page_url: "string",
                page_description: "string",
                netflix_link: "string",
                created_at: null,
                updated_at: null,
              },
            ],
            product_statusDto: [
              {
                product_status_id: 1,
                product_status_en: null,
                product_status_ar: "string",
                product_status_details_ar: "string",
                product_status_details_en: null,
                created_at: null,
                updated_at: null,
              },
            ],
            moreDto: [
              {
                more_id: 1,
                more_en: null,
                more_ar: "string",
                more_details_ar: "string",
                more_details_en: null,
              },
            ],
            trade_marksDto: [
              {
                trade_mark_id: 1,
                trade_mark_name_en: null,
                trade_mark_name_ar: "علامة تجارية جديدة",
                trade_mark_details_en: null,
                trade_mark_details_ar:
                  "تفاصيل العلامة التجارية الجديدة باللغة العربية",
              },
              {
                trade_mark_id: 2,
                trade_mark_name_en: null,
                trade_mark_name_ar: "علامة تجارية جديدة",
                trade_mark_details_en: null,
                trade_mark_details_ar:
                  "تفاصيل العلامة التجارية الجديدة باللغة العربية",
              },
            ],
            ratingDto: [],
          },
        ],
        trade_marksDto: [
          {
            trade_mark_id: 1,
            trade_mark_name_en: null,
            trade_mark_name_ar: "علامة تجارية جديدة",
            trade_mark_details_en: null,
            trade_mark_details_ar:
              "تفاصيل العلامة التجارية الجديدة باللغة العربية",
          },
          {
            trade_mark_id: 2,
            trade_mark_name_en: null,
            trade_mark_name_ar: "علامة تجارية جديدة",
            trade_mark_details_en: null,
            trade_mark_details_ar:
              "تفاصيل العلامة التجارية الجديدة باللغة العربية",
          },
        ],
      },
    ],
  },
  {
    category_id: 2,
    category_name_en: null,
    category_name_ar: "clothes",
    details_en: null,
    details_ar: "التصميم,الطباعه",
    created_at: "2025-01-16T05:44:42.3213401",
    updated_at: "2025-01-16T05:44:42.3213492",
    brandsDto: [],
  },
  {
    category_id: 3,
    category_name_en: null,
    category_name_ar: "Food",
    details_en: null,
    details_ar: "الماكولات والمشروبات",
    created_at: "2025-01-16T05:45:07.6150025",
    updated_at: "2025-01-16T05:45:07.6150326",
    brandsDto: [
      {
        brand_id: 2,
        brand_name: "food",
        details: "عامه",
        add_to_main_brand: true,
        created_at: null,
        updated_at: null,
        productDto: [],
        trade_marksDto: [
          {
            trade_mark_id: 1,
            trade_mark_name_en: null,
            trade_mark_name_ar: "علامة تجارية جديدة",
            trade_mark_details_en: null,
            trade_mark_details_ar:
              "تفاصيل العلامة التجارية الجديدة باللغة العربية",
          },
          {
            trade_mark_id: 2,
            trade_mark_name_en: null,
            trade_mark_name_ar: "علامة تجارية جديدة",
            trade_mark_details_en: null,
            trade_mark_details_ar:
              "تفاصيل العلامة التجارية الجديدة باللغة العربية",
          },
        ],
      },
    ],
  },

  {
    category_id: 5,
    category_name_en: null,
    category_name_ar: "Digital",
    details_en: null,
    details_ar: "بطاقات شحن",
    created_at: "2025-01-16T05:46:07.5039791",
    updated_at: "2025-01-16T05:46:07.5039865",
    brandsDto: [],
  },
];
